version: "3.9"

services:
  db:
    ports:
      - "${DB_PORT:-3306}:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 300M
    depends_on:
      db:
        condition: service_healthy
    profiles: ["dev"]

  app:
    ports:
      - "${PORT:-3000}:3000"
    command: >
      sh -c "npx prisma generate && npx prisma migrate dev && npx nodemon --exec ts-node ./src/index.ts"
    volumes:
      - .:/opt/checkin-app
      - /opt/checkin-app/node_modules
    profiles: ["dev"]
