version: "3.9"

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      TZ: "UTC"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 300M
    depends_on:
      db:
        condition: service_healthy
    profiles: ["dev"]

  app:
    build:
      context: .
      dockerfile: ./Containerfile
    container_name: node_app
    restart: always
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    volumes:
      - ./.env:/opt/checkin-app/.env
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "npx prisma migrate deploy && npm start"
    profiles: ["dev", "prod", "homol"]

volumes:
  db_data:
