export enum LoggerContext {
  COMMAND = "COMMAND",
  INFRASTRUCTURE = "INFRASTRUCTURE",
  APP_CONTEXT = "APP CONTEXT",
  REPOSITORY = "REPOSITORY",
  SERVICE = "SERVICE",
  USECASE = "USECASE",
  CONTROLLER = "CONTROLLER",
}

export enum LoggerContextEntity {
  USER = "USER",
  USER_EVENT = "USER_EVENT",
  MESSAGE = "MESSAGE",
  MESSAGE_REACTION = "MESSAGE_REACTION",
  CHANNEL = "CHANNEL",
  AUDIO_EVENT = "AUDIO_EVENT",
  ROLE = "ROLE",
}

export enum LoggerContextStatus {
  SUCCESS = "SUCCESS",
  ERROR = "ERROR",
}
